[workspace]
members = ["geozero", "geozero-shp", "geozero-cli", "geozero-bench", "geozero-arrow"]
default-members = ["geozero", "geozero-shp", "geozero-cli", "geozero-arrow"]

[patch.crates-io]
geozero = { path = "geozero" }
#flatgeobuf = { path = "../../gis/flatgeobuf/src/rust" }
